"""add indexes

Revision ID: 4ce27f9d31e3
Revises: 09ec4d84d827
Create Date: 2026-07-26 12:35:50.681612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ce27f9d31e3'
down_revision: Union[str, Sequence[str], None] = '09ec4d84d827'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")   # <-- добавьте эту строку
    op.create_index('idx_items_created_at', 'items', ['created_at'], unique=False)
    op.create_index(
        'idx_items_description_trgm',
        'items',
        ['description'],
        unique=False,
        postgresql_using='gin',
        postgresql_ops={'description': 'gin_trgm_ops'}
    )
    op.create_index('idx_items_name', 'items', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_items_name', table_name='items')
    op.drop_index('idx_items_description_trgm', table_name='items', postgresql_using='gin')
    op.drop_index('idx_items_created_at', table_name='items')
    # ### end Alembic commands ###
