"""create items table with indexes

Revision ID: 8f49a3c99e05
Revises: 
Create Date: 2026-07-26 20:00:07.401919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f49a3c99e05'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_items_created_at', 'items', ['created_at'], unique=False)
    op.create_index('idx_items_description_trgm', 'items', ['description'], unique=False, postgresql_using='gin', postgresql_ops={'description': 'gin_trgm_ops'})
    op.create_index('idx_items_name', 'items', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_items_name', table_name='items')
    op.drop_index('idx_items_description_trgm', table_name='items', postgresql_using='gin', postgresql_ops={'description': 'gin_trgm_ops'})
    op.drop_index('idx_items_created_at', table_name='items')
    op.drop_table('items')
    # ### end Alembic commands ###
